name: Network unit tests
on:
  push:
      # Publish `master` as Docker `latest` image.
      branches:
        - master
        - develop
        - feature/**
        - release/**
        - hotfix/**
      # Publish `v1.2.3` tags as releases.
      tags:
        - v*
  pull_request:
    branches: 
      - master
      - develop

jobs:
  network-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source
        uses: actions/checkout@v1

      - name: Install .NET SDK 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: "Build unit tests"
        run: dotnet test SensateIoT.Platform.Network.Tests/SensateIoT.Platform.Network.Tests.csproj
